Add geoColumn & columns props to CartoLayer
visgl/deck.gl pull request #6097
Opened 2021-08-13 12:37 UTC by felixpalmer

Implementation of https://github.com/visgl/deck.gl/issues/6096

2021-08-13 14:03 UTC, alasarr commented on modules/carto/src/layers/carto-layer.js
> +  connection: null,
Need to add these parameters at the doc

2021-08-13 14:04 UTC, alasarr commented on modules/carto/src/layers/carto-layer.js
> +  connection: null,
Would be great to explain that default value is `geom`

2021-08-13 14:04 UTC, alasarr requested changes
Looks good to me, but need to update the doc

2021-08-13 14:59 UTC, Pessimistress commented on modules/carto/src/layers/carto-layer.js
> +  columns: null
If you declare `type: 'array'` here then the layer diff will block unnecessary updates unless the prop changes deeply

2021-08-19 10:39 UTC, alasarr commented on modules/carto/src/api/maps-v3-client.js
> +  if (geoColumn) {
This parameter is only available for MAP_TYPES.TABLE, shouldn't be passed in other cases

2021-08-19 10:40 UTC, alasarr commented on docs/api-reference/carto/carto-layer.md
> +##### `geoColumn` (String, optional)
We need to say that this parameter is only supported for `MAP_TYPES.TABLE`, so only available in v3 because type table is only supported in V3+

2021-08-19 10:41 UTC, alasarr commented on docs/api-reference/carto/carto-layer.md
> +##### `columns` (Array<String>, optional)
Same as before.

2021-08-19 10:43 UTC, alasarr commented on modules/carto/src/layers/carto-layer.js
> +      if (columns) {
Need to check columns and geoColumn are only allow for `MAP_TYPES.TABLE`

2021-08-22 06:56 UTC, alasarr approved these changes

2021-08-23 08:21 UTC, merged