CARTO module: Support tiles in different formats
visgl/deck.gl pull request #6609
Opened 2022-01-31 13:03 UTC by padawannn

#### Background
Currently, the Carto module always uses the MVT layer to load any tileset. Now, we read the tile format from the Maps API and we use the MVT layer or the Carto Dynamic Tile Layer that support tiles in other formats like geojson or binary
#### Change List
- Read the tile format from the Maps API to decide to load an MVT layer or a Carto Dynamic Tile Layer

2022-01-31 15:40 UTC, felixpalmer requested changes
Nice, thanks. Just a few nits

2022-01-31 15:40 UTC, felixpalmer commented on modules/carto/src/api/maps-api-common.js
> +export const TILES_FORMATS = {
I think `TILE_FORMATS` is a better name

2022-02-01 16:49 UTC, padawannn commented on modules/carto/src/api/maps-api-common.js
> +export const TILES_FORMATS = {
Done

2022-02-01 16:49 UTC, padawannn commented on modules/carto/src/layers/carto-layer.js
> +    if (apiVersion === API_VERSIONS.V3 && format === FORMATS.TILEJSON) {
Done

2022-02-01 18:09 UTC, felixpalmer approved these changes

2022-02-02 09:22 UTC, merged