[ts] CartoTileLayer and utilities
visgl/deck.gl pull request #6891
Opened 2022-05-06 07:17 UTC by zbigg

For #5589

Change List:

* Convert `CartoTileLayer` to Typescript
* Convert Carto Tile protobuf-based parser to Typescript
* Minor improvements to typings in `CompositeLayer`, `MVTLayer` and `TileLayer`

2022-05-31 14:46 UTC, felixpalmer requested changes

2022-05-31 15:08 UTC, zbigg commented on modules/carto/src/layers/carto-tile-layer.ts
> +  return data as unknown as BinaryFeatures;
I really don't know at this point that is the exact reason of why i needed cast here. 
I've assumed this is correct, tested code (ran some tests on real data too and "it works" with real data).

2022-05-31 15:08 UTC, zbigg commented on modules/geo-layers/src/index.ts
> +  GeoBoundingBox as _GeoBoundingBox
Leftover, removed.

2022-06-01 07:44 UTC, felixpalmer commented on modules/carto/package.json
> +    "@loaders.gl/schema": "^3.2.0-alpha.4"
OK fair enough

2022-06-01 07:45 UTC, felixpalmer approved these changes

2022-06-01 07:46 UTC, merged