CARTO: fetchMap support spatial index layers
visgl/deck.gl pull request #7065
Opened 2022-06-20 16:01 UTC by felixpalmer

For https://github.com/visgl/deck.gl/issues/6912

#### Change List
- Unify layer selection based on tileset definition between `CartoLayer` & `fetchMap`
- Generate spatial index tile layers in fetchMap
- Tests

2022-06-21 08:51 UTC, padawannn requested changes
@felixpalmer I think that you're not building the `aggregationExp` from the layer style? Have you tried to style a map by a property in builder and check if it works with the fetchMap?

2022-06-21 15:29 UTC, felixpalmer commented
> `aggregationExp`

@padawannn No, you're right - that is missing. Could you point me at where that is done in builder? I can't seem to find the code

2022-06-22 06:32 UTC, alasarr submitted a review, later dismissed

2022-06-22 06:32 UTC, alasarr commented on modules/carto/src/api/layer-map.ts
> +export function layerFromTileDataset(
👍

2022-06-22 06:34 UTC, alasarr commented
>@padawannn No, you're right - that is missing. Could you point me at where that is done in builder? I can't seem to find the code

You can try at dedicated server 05, click on layer and fill by color based on a property

2022-07-14 16:37 UTC, padawannn requested changes

2022-07-18 11:12 UTC, padawannn approved these changes

2022-07-18 13:21 UTC, merged