Carto fetchmap markers
visgl/deck.gl pull request #7250
Opened 2022-09-08 08:23 UTC by zbigg

#### Background

Carto `fetchMap` shall support custom markers. 

#### Change List
* fetchMap supports custom map markers
* new tests for fetchMap

2022-09-08 11:04 UTC, zbigg commented on modules/carto/src/api/layer-map.ts
> +const FALLBACK_ICON =
This is just filled circle in SVG.

2022-09-08 13:13 UTC, felixpalmer requested changes
Nice job :)

2022-09-08 13:52 UTC, zbigg commented on modules/carto/src/api/layer-map.ts
> +    ? (d, oi) => {
I was trying to be too type-correct, more than reasonable, accessors are ours and they don't need `oi` removed this excessive typing

2022-09-08 13:58 UTC, zbigg commented on modules/carto/src/api/parseMap.ts
> +  let result: Record<string, any> = {};
OTOH _i_ was unhappy with having too much random stuff in result not necessary needed for this particular mode of layer rendering.
So both are suboptimal :/
I am reverting to original approach.

2022-09-08 16:04 UTC, zbigg commented on modules/carto/src/api/parseMap.ts
> +      result.getIconColor = config.color;
[Here](https://github.com/visgl/deck.gl/pull/7250/commits/12df761092256060f6fbfa8490e000b4a38bdc80) I've created customPropMap that is created for layers with customMarkers, let's see if it's looks & feels better

2022-09-09 08:37 UTC, felixpalmer approved these changes

2022-09-14 10:37 UTC, felixpalmer approved these changes

2022-09-14 12:43 UTC, merged