Fix SimpleMeshLayerProps wireframe type
visgl/deck.gl pull request #7556
Opened 2023-01-04 12:07 UTC by thpica

For #7555

#### Background

#### Change List
- Fix SimpleMeshLayerProps wireframe type

2023-01-04 13:15 UTC, felixpalmer requested changes

2023-01-04 13:15 UTC, felixpalmer commented on modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.ts
> +  wireframe?: boolean;
Apply the same fix to `_instanced`?

2023-01-06 12:57 UTC, thpica commented on modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.ts
> +  wireframe?: boolean;
Done

2023-01-06 17:16 UTC, Pessimistress approved these changes

2023-01-06 18:52 UTC, merged