Update documentation for TileLayer
visgl/deck.gl pull request #7905
Opened 2023-05-19 13:05 UTC by kopp

Document that getTileMetadata is not optional and what to return from it.

2023-05-19 13:10 UTC, kopp commented
@felixpalmer : I think this was the solution to the problems I reported in #6816 .  Can you do me the honor of reviewing the pull request?

2023-05-23 07:43 UTC, felixpalmer requested changes

2023-05-23 07:43 UTC, felixpalmer commented on docs/api-reference/geo-layers/tile-layer.md
> +- `getTileIndices({viewport, maxZoom, minZoom, zRange, modelMatrix, modelMatrixInverse})` - returns an array of indices in the given viewport. The indices should have the shape of Objects, like `{q:
I don't think this addition is needed

2023-05-23 07:43 UTC, felixpalmer commented on docs/api-reference/geo-layers/tile-layer.md
> +- `getTileMetadata(index)` - returns additional metadata to add to tile.  This must be an object that contains a bounding box as `bbox` in the format `{west: number, south: number, east: number, nort
Looks good 👍

2023-05-30 12:17 UTC, kopp commented on docs/api-reference/geo-layers/tile-layer.md
> +- `getTileIndices({viewport, maxZoom, minZoom, zRange, modelMatrix, modelMatrixInverse})` - returns an array of indices in the given viewport. The indices should have the shape of Objects, like `{q:
ok, removed :)

2023-05-30 12:18 UTC, kopp commented
Thanks for looking at this.  I removed the first change.

2023-05-31 09:17 UTC, felixpalmer approved these changes

2023-05-31 09:18 UTC, merged