[8.9] Added new numSegments prop in ArcLayer
visgl/deck.gl pull request #8055
Opened 2023-08-13 13:48 UTC by karsta26

For #8052

#### Background
Added a new parameter to be able to modify the number of segments used to generate arcs. Previously the number was hardcoded - 50. 
This will allow rendering smooth arcs in case of long paths with `greatCircle` param.
#### Change List
- Added new `numSegments` prop in `ArcLayer`
- Fixed some broken links

2023-08-16 10:50 UTC, felixpalmer commented on test/render/golden-images/great-circle-modified-segments.png
The render output looks strange to me, any idea why those lines are becoming thin and forming the square shapes? It's quite different from the `great-circle.png` output

2023-08-16 10:53 UTC, felixpalmer commented on test/render/golden-images/great-circle-modified-segments.png
I think perhaps a better test case is one demonstrating what this PR is for, i.e. `numSegments > 50` showing a zoomed-in portion of a curve that is now smooth, whereas before it had visible segments - like you have in the [Issue](https://github.com/visgl/deck.gl/issues/8052)

2023-08-17 19:41 UTC, karsta26 commented on test/render/golden-images/great-circle-modified-segments.png
Regarding square shapes:
This is due to a projection and very long paths that are used in this example. 

To better visualize this: this is the data from the `great-circle` test case shown on a map with countries with `numSegments = 50`.
![image](https://github.com/visgl/deck.gl/assets/24994759/d7a6a6d7-e64f-4e49-b83a-f18e9351da94)

And this is the same data but with `numSegments = 8` as in the new test.
![image](https://github.com/visgl/deck.gl/assets/24994759/3d48b5a4-a322-4827-ae97-45e5e74fd1ec)

As you can see for the very long path there are not enough segments to draw it properly and because of this square shape is visible. 


I agree that perhaps this is not the best way to demonstrate the new parameter.
I have changed the test case to have only one arc. 

With the default value of the parameter, the test fails and produces this image:
![image](https://github.com/visgl/deck.gl/assets/24994759/f9850546-0c99-4e06-9aaa-75cdcd104ef6)

And with `numSegments = 150` the new golden image:
![image](https://github.com/visgl/deck.gl/assets/24994759/6537700d-b226-4f8b-8fac-8a12df4aae9e)

2023-08-21 13:12 UTC, felixpalmer requested changes

2023-08-21 18:58 UTC, karsta26 commented on modules/layers/src/arc-layer/arc-layer.ts
> +  numSegments: {type: 'number', value: 50, min: 0},
Changed to 1

2023-08-22 07:27 UTC, felixpalmer approved these changes

2023-08-29 19:12 UTC, merged