CARTO: Add example for boundaries
visgl/deck.gl pull request #8269
Opened 2023-11-08 13:57 UTC by felixpalmer

For https://github.com/visgl/deck.gl/issues/8148

#### Change List

- Add `CartoPropertiesTileLoader` to load binary property tile data
- Enhance `VectorTileLayer` to support fetching & merging of property data
- Add `cartoBoundaryQuerySource` & `cartoBoundaryTableSource`
- Update test app with query & table boundary examples

2023-11-08 19:00 UTC, alasarr requested changes

2023-11-09 09:09 UTC, felixpalmer commented on modules/carto/src/sources/boundary-query-source.ts
> +import {baseSource} from './base-source';
As discussed, it's better to be explicit & consistent and add a `boundaryTilesetSource` which has no such property

2023-11-09 10:51 UTC, alasarr commented on modules/carto/src/sources/boundary-query-source.ts
> +  propertiesSqlQuery: string;
rename to sqlQuery

2023-11-09 10:51 UTC, alasarr commented on modules/carto/src/sources/boundary-table-source.ts
> +  propertiesTableName: string;
tableName

2023-11-09 10:52 UTC, alasarr commented on modules/carto/src/sources/boundary-table-source.ts
> +  matchingPropertyName?: string;
matchingColumn

2023-11-09 13:20 UTC, alasarr requested changes
Just a small thing detected

2023-11-09 13:20 UTC, alasarr commented on docs/api-reference/carto/data-sources.md
> +  columns?: string[];
Why is this required?  In tileset we don't support columns as the API cannot filter by them

2023-11-09 13:20 UTC, alasarr commented on modules/carto/src/sources/boundary-tileset-source.ts
> +  if (columns) {
Not required

2023-11-09 13:40 UTC, alasarr approved these changes

2023-11-09 13:41 UTC, alasarr commented on docs/api-reference/carto/data-sources.md
> +#### boundaryTableSource
We should mark this as experimental

2023-11-09 16:17 UTC, merged