Imorove Tile3DLayer.isLoaded
visgl/deck.gl pull request #8279
Opened 2023-11-12 16:01 UTC by chrisgervang

For #8260

#### Change List
- Add protections to Tile3DLayer.isLoaded

2023-11-12 16:03 UTC, chrisgervang commented
Should I open a second PR for v9 since that file is "disabled"?

2023-11-13 10:26 UTC, felixpalmer requested changes

2023-11-13 10:26 UTC, felixpalmer commented on modules/geo-layers/src/tile-3d-layer/tile-3d-layer.ts
> +    return Boolean(
```suggestion
    return Boolean(this.state?.tileset3d?.isLoaded() && super.isLoaded)
```

Like we do in `TileLayer`

2023-11-13 10:27 UTC, felixpalmer commented
> Should I open a second PR for v9 since that file is "disabled"?

That would be great

2023-11-13 18:37 UTC, chrisgervang commented
@felixpalmer good to go?

2023-11-14 09:26 UTC, felixpalmer approved these changes

2023-11-15 00:36 UTC, merged