feat(examples): Port remaining shaders to GLSL 300 ES
visgl/deck.gl pull request #8433
Opened 2024-01-18 18:48 UTC by donmccurdy

For https://github.com/visgl/deck.gl/issues/7457. Ports remaining GLSL (that I could find in code search, anyway) to GLSL 300. I see various errors when trying to start these examples — should they be working? — but the changes here shouldn't be the cause.

2024-01-18 18:49 UTC, donmccurdy commented
Current dependencies on/for this PR:
* `master`
  * **PR #8433** <a href="https://app.graphite.dev/github/pr/visgl/deck.gl/8433?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/visgl/deck.gl/8433?utm_source=stack-comment).

2024-01-19 09:42 UTC, felixpalmer commented
I came across these as well, but hesitate to change them if they are not working. They are old examples, which as you say were written against an old version of deck. As they are not present on the website, I don't see them as high priority to fix. 

Changing the shaders to GLSL 300 without making them work in v9 will mean they are broken in all versions of deck.gl, so perhaps a better option for now is to add a comment stating what version they work against and if someone wants to port them in the future, they can

2024-01-19 09:44 UTC, felixpalmer requested changes
For the examples which do not work, could you verify which version of deck these were written against (or work with) and add a comment rather than porting the shaders

2024-01-19 18:57 UTC, donmccurdy commented
Thanks, I've added versions to the description above — the working example uses v8, the broken examples use v6 and v5. 

I'm a bit concerned that there's so much dead code: it is more difficult to know when migration tasks are finished as a result. If these examples are available on their respective release branches, and haven't been updated since the v7 release (5 years ago) then I am inclined to suggest they shouldn't be on the master branch going into v9.

2024-01-22 09:11 UTC, felixpalmer commented
> I'm a bit concerned about having chunks of dead code

I agree, v5 & 6 are very old. How about you remove the broken examples from this PR and make another PR which just removes them from the codebase, so we give the others a chance to comment?

2024-03-07 20:00 UTC, donmccurdy commented
I've removed the changes to the "ascii" and "wind" showcases from this PR, so now it only affects `examples/experimental/bezier`, which I've tested. I posted a thread in Slack about removing the `showcases/` folder, but haven't gotten replies on that, so inclined to just leave those alone for now.

2024-03-08 10:18 UTC, felixpalmer approved these changes

2024-03-08 14:38 UTC, merged