[Docs] fix typos
visgl/deck.gl pull request #8448
Opened 2024-01-23 14:13 UTC by jamesscottbrown

Fix #8172

2024-01-23 16:46 UTC, cgalvan approved these changes

2024-01-24 08:50 UTC, felixpalmer requested changes

2024-01-24 08:50 UTC, felixpalmer commented on docs/developer-guide/using-layers.md
> +* The framework then then makes the minimal necessary changes to account for the differences, and then redraws.
```suggestion
* The framework then makes the minimal necessary changes to account for the differences, and then redraws.
```

2024-01-24 14:13 UTC, felixpalmer approved these changes

2024-02-21 00:53 UTC, merged