test PR: Bump to loaders@4.2-beta
visgl/deck.gl pull request #8771
Opened 2024-04-08 22:10 UTC by ibgreen

Closes #

#### Background

#### Change List
-

2024-04-09 17:45 UTC, Pessimistress commented
```
% yarn list "@loaders.gl/*"
yarn list v1.22.19
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @loaders.gl/3d-tiles@4.2.0
├─ @loaders.gl/compression@4.2.0
├─ @loaders.gl/core@4.2.0
├─ @loaders.gl/crypto@4.2.0
├─ @loaders.gl/csv@4.2.0
├─ @loaders.gl/draco@4.2.0
├─ @loaders.gl/gis@4.2.0
├─ @loaders.gl/gltf@4.2.0
├─ @loaders.gl/images@4.2.0
├─ @loaders.gl/loader-utils@4.2.0
├─ @loaders.gl/math@4.2.0
├─ @loaders.gl/mvt@4.2.0
├─ @loaders.gl/polyfills@4.2.0
├─ @loaders.gl/schema@4.2.0
├─ @loaders.gl/terrain@4.2.0
├─ @loaders.gl/textures@4.2.0
├─ @loaders.gl/tiles@4.2.0
├─ @loaders.gl/wms@4.2.0
├─ @loaders.gl/worker-utils@4.2.0
├─ @loaders.gl/xml@4.2.0
├─ @loaders.gl/zip@4.2.0
└─ @luma.gl/gltf@9.0.9
   ├─ @loaders.gl/images@4.1.4
   ├─ @loaders.gl/loader-utils@4.1.4
   ├─ @loaders.gl/schema@4.1.4
   ├─ @loaders.gl/textures@4.1.4
   └─ @loaders.gl/worker-utils@4.1.4
✨  Done in 0.61s.
```

2024-04-09 18:00 UTC, ibgreen commented
That's a surprise.. I would have assumed that the carets in loaders.gl package.json would have led to the same version being used across the board for all loaders.gl deps. 

How would you like to handle it?

- I put up a PR in loaders.gl: https://github.com/visgl/luma.gl/pull/2068
- or we could bump the loaders version in the yarn.lock file here in deck
- or just leave as is and let apps upgrade themselves

2024-04-09 18:00 UTC, Pessimistress requested changes
Some v4.1 are still present in the dependency tree.

2024-04-09 18:04 UTC, Pessimistress commented
@ibgreen 
- Bumping top-level dep versions does not affect nested deps
- We need to update all deps in this repo for pre-built bundles to be generated correctly
- We should bump the deps in luma, but for this PR you just need to fix yarn.lock

2024-04-10 18:51 UTC, Pessimistress approved these changes

2024-04-10 18:59 UTC, merged