chore(docs): Formatting and deck.gl-community link
visgl/deck.gl pull request #8792
Opened 2024-04-15 22:50 UTC by ibgreen

Closes #

#### Background

#### Change List
- formatting improvements
- remove some dated references, rewrite some intro text
- reformat README page and learning resources page.
- Add deck.gl-community repo mention

2024-04-16 01:25 UTC, Pessimistress commented
Can you split the yarn version change to its own PR? I'm not sure how Volta will work on CI, if at all.

2024-04-19 00:00 UTC, Pessimistress requested changes

2024-04-19 11:13 UTC, ibgreen commented on docs/README.md
> +| deck.gl Flavor            | Installed via                                                          | Get Started                                                              | Examples
Restored.

2024-04-19 15:45 UTC, Pessimistress approved these changes

2024-04-19 16:58 UTC, merged